version: 2
jobs:
  build:
    docker:
      - image: 303634175659.dkr.ecr.us-east-2.amazonaws.com/circleci:cl-housing-cars
        aws_auth:
          aws_access_key_id: $AWS_ACCESS_KEY_ID
          aws_secret_access_key: $AWS_SECRET_ACCESS_KEY
    steps:
      - checkout

      # ... steps for building/testing app ...

      - setup_remote_docker:   # (2)
          docker_layer_caching: false # (3)

      # build and push Docker image
      - run: |
          ./docker-build.sh
